# Generated by Django 4.1.7 on 2023-03-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name1', models.CharField(max_length=50)),
                ('last_name1', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone1', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
    ]
