# Generated by Django 4.1.7 on 2023-03-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='phone1',
            field=models.IntegerField(),
        ),
    ]
