# Generated by Django 4.1.7 on 2023-04-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_appointment_phone1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
