# Generated by Django 4.1.7 on 2023-04-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactbuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'contactbuy',
            },
        ),
    ]
