# Generated by Django 4.1.7 on 2023-04-14 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('builders_name', models.CharField(max_length=50)),
                ('rera', models.BooleanField(default=True)),
                ('construction_year', models.DateField()),
                ('photos', models.ImageField(default=True, upload_to='media')),
            ],
            options={
                'db_table': 'property_info',
            },
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('for_rent', models.BooleanField(default=False)),
                ('for_sell', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('Property_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='property.property_info')),
            ],
            options={
                'db_table': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property_info')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_team',
            },
        ),
    ]
