# Generated by Django 4.1.7 on 2023-04-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_info',
            name='price',
            field=models.IntegerField(default=True),
        ),
    ]
