# Generated by Django 4.1.7 on 2023-04-17 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_info_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'city_name',
            },
        ),
        migrations.CreateModel(
            name='Property_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'type_name',
            },
        ),
        migrations.AddField(
            model_name='property_info',
            name='garden',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='property_info',
            name='price',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='property_info',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='property.city'),
        ),
        migrations.AddField(
            model_name='property_info',
            name='property_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='property.property_type'),
        ),
    ]
